v1.0.6

diff --git a/.github/workflows/create_project_api.yml b/.github/workflows/create_project_api.yml
--- a/.github/workflows/create_project_api.yml
+++ b/.github/workflows/create_project_api.yml
@@ -44,6 +44,8 @@ jobs:
             echo "ERROR    | Unable to create project."
             exit 1
           }
+          project_id=$(echo "$run" | jq -r '.data."id"')
+          echo "project_id=${project_id}" >> "${GITHUB_OUTPUT}"
 
       - name: Create team
         id: create_team
@@ -103,5 +105,31 @@ jobs:
             echo "ERROR    | Unable to create team token."
             exit 1
           }
-          token=$(echo "$run" | jq -r '.data.attribute."token"')
+          token=$(echo "$run" | jq -r '.data.attributes."token"')
           echo "INFO     | Token: ${token}"
+
+      - name: Create team project access
+        run: |
+          echo "INFO     | Building required variables."
+          tfc_api_url="https://app.terraform.io/api/v2"
+          auth_header="Authorization: Bearer ${TF_API_TOKEN}"
+          content_header="Content-Type: application/vnd.api+json"
+          echo "INFO     | Building JSON payload."
+          json_string='{"data":{"attributes":{"access":"custom","workspace-access":{"runs":"apply","variables":"write"}},"relationships":{"project":{"data":{"type":"projects","id":"'"${{ steps.create_project.outputs.project_id }}"'"}},"team":{"data":{"type":"teams","id":"'"${{ steps.create_team.outputs.team_id }}"'"}}},"type": "team-projects"}}'
+          json_payload=$(echo "${json_string}" | jq)
+          echo "INFO     | Running API call to create team project access."
+          {
+            run=$(curl -sS --request POST --url "${tfc_api_url}/team-projects" \
+            --header "${auth_header}" --header "${content_header}" --data "${json_payload}")
+            if ! [[ "${run}" =~ "{\"data\":" ]]; then
+              echo "ERROR    | Unable to create team project access."
+              echo "${run}"
+              exit 1
+            else
+              echo "INFO     | Team project access created."
+            fi
+          } ||
+          {
+            echo "ERROR    | Unable to create team project access."
+            exit 1
+          }
